Repository OpenDevUFCG/glossario-ufcg, pull requests merged in 2019-10, with the labels that each got.

#118 Adição de comando 'git add' após ordenação dos dados pelo script de p…
  package.json
Labels: Bug, Configuração

#128 add Header component w/ react-router-prop-types
  package.json
  src/components/common/Header/Header.css
  src/components/common/Header/Header.js
  src/components/glossary/GlossaryPage.css
  src/components/glossary/GlossaryPage.js
  yarn.lock
Labels: Refatoramento

#134 Adiciona favicon
  webpack/webpack.common.js
Labels: Aprimoramento, Configuração, Frontend

#131 Adiciona script de prettier
  package.json
  public/swRegister.js
  src/components/app/App.css
  src/components/app/Footer/Footer.css
  src/components/common/Header/Header.css
  src/components/common/Header/Header.js
  src/components/common/Icon/IconWithText/IconWithText.css
  src/components/common/Search/Search.css
  src/components/common/TermCard/TermCard.css
  src/components/glossary/GlossaryPage.css
  src/components/glossary/results/SearchResults.css
  src/components/glossary/results/SearchResults.js
  src/index.css
  src/index.html
  src/styles/odu/colors.css
  src/styles/odu/odu.css
  src/styles/utils.css
  webpack/webpack.common.js
  webpack/webpack.dev.js
  webpack/webpack.prod.js
Labels: Aprimoramento, Configuração

#133 Normalizando o código com as regras predefinidas do eslint. Adicionando (verificação eslint) dentro da pipeline do travis.
  .eslintignore
  .travis.yml
  package.json
  src/components/common/Icon/Icon.js
  src/components/common/Search/Search.js
  src/components/common/TermCard/TermCard.js
  src/components/glossary/GlossaryPage.js
  src/components/glossary/results/404/NotFound.js
  src/components/glossary/results/SearchResults.js
  src/scripts/orderData.js
Labels: Aprimoramento, Configuração, Refatoramento

#149 Adicionado Mapa no Cartão do Termo. #93
  assets/images/map-pin.png
  package.json
  src/components/common/LocationIfExists/LocalizationIfExists.js
  src/components/common/TermCard/TermCard.css
  src/components/common/TermCard/TermCard.js
  src/lib/locais.json
  yarn.lock
Labels: Aprimoramento, Feature
