Repository OpenDevUFCG/glossario-ufcg, pull requests merged in 2019-03, with the labels that each got.

#40 Ui refactor
  assets/images/glossario-logo.svg
  src/components/Footer/GlossaryFooter.css
  src/components/Footer/GlossaryFooter.js
  src/components/Glossary/Glossary.css
  src/components/Glossary/Glossary.js
  src/components/Icon/Icon.js
  src/components/IconButton/IconButton.js
  src/components/IconWithText/IconWithText.css
  src/components/IconWithText/IconWithText.js
  src/components/app/App.css
  src/components/app/App.js
Labels: design, frontend

#43 Adiciona new_term template
  .github/ISSUE_TEMPLATE/new_term.md
Labels: enhancement, mutirão de carnaval

#45 Finalize ui design
  src/components/Footer/GlossaryFooter.css
  src/components/Footer/GlossaryFooter.js
  src/components/Glossary/Glossary.css
  src/components/Glossary/Glossary.js
  src/components/Icon/Icon.js
  src/components/IconWithText/IconWithText.css
  src/components/IconWithText/IconWithText.js
  src/components/search/Search.css
  src/components/search/Search.js
  src/styles/odu/colors.css
  src/styles/utils.css
Labels: design, enhancement, frontend

#50 Troca BrowserRouter pelo HashRouter
  src/index.js
Labels: bug, frontend

#51 Componente de AutoComplete
  package.json
  src/components/Description/Description.css
  src/components/Description/Description.js
  src/components/Glossary/Glossary.js
  src/components/SelectionBar/SelectionBar.js
  src/components/VerticalSeparator/VerticalSeparator.css
  src/components/VerticalSeparator/VerticalSeparator.js
  src/components/search/Search.css
  src/components/search/Search.js
  yarn.lock
Labels: enhancement, frontend

#56 Glossario responsivo
  src/components/Footer/GlossaryFooter.css
  src/components/Glossary/Glossary.css
  src/components/IconWithText/IconWithText.css
  src/components/search/Search.css
  src/index.html
  src/lib/disciplinas.json
  src/lib/girias.json
Labels: design, enhancement, frontend, nova ui

#55 Card de significados
  src/components/ResultCard/ResultCard.css
  src/components/ResultCard/ResultCard.js
  src/index.css
  src/index.html
Labels: enhancement, frontend

#62 Adiciona descrição dos termos IA, CDP, AS, BD
  src/lib/disciplinas.json
Labels: mutirão de carnaval

#68 Card exhibition
  src/components/Glossary/Glossary.css
  src/components/Glossary/Glossary.js
  src/components/ResultCard/ResultCard.css
  src/components/ResultCard/ResultCard.js
  src/components/ResultsPage/ResultsPage.css
  src/components/ResultsPage/ResultsPage.js
  src/components/app/App.js
  src/components/search/Search.css
  src/components/search/Search.js
Labels: enhancement, frontend, nova ui

#71 Nova interface
  assets/fonts/Ikaros-Regular.otf
  assets/fonts/Jaapokki-Regular.otf
  assets/images/favicon.ico
  assets/images/glossario-icon.png
  assets/images/glossario-logo.svg
  assets/images/pattern.png
  package.json
  src/components/Description/Description.css
  src/components/Description/Description.js
  src/components/Footer/GlossaryFooter.css
  src/components/Footer/GlossaryFooter.js
  src/components/Glossary/Glossary.css
  src/components/Glossary/Glossary.js
  src/components/Icon/Icon.js
  src/components/IconButton/IconButton.js
  src/components/IconWithText/IconWithText.css
  src/components/IconWithText/IconWithText.js
  src/components/ResultCard/ResultCard.css
  src/components/ResultCard/ResultCard.js
  src/components/ResultsPage/ResultsPage.css
  src/components/ResultsPage/ResultsPage.js
  src/components/SelectionBar/SelectionBar.js
  src/components/VerticalSeparator/VerticalSeparator.css
  src/components/VerticalSeparator/VerticalSeparator.js
  src/components/app/App.css
  src/components/app/App.js
  src/components/search/Search.css
  src/components/search/Search.js
  src/index.css
  src/index.html
  src/index.js
  src/lib/disciplinas.json
  src/lib/outros.json
  src/styles/odu/colors.css
  src/styles/utils.css
  webpack.config.js
  yarn.lock
Labels: design, enhancement, frontend

#74 Conserta centralização de logo
  src/components/Glossary/Glossary.js
Labels: bug, frontend

#53 Incrementa conteúdo de LP2 e OAC
  src/lib/disciplinas.json
  src/lib/locais.json
Labels: mutirão de carnaval

#86 Adicionando configuração de produção do webpack
  package.json
  webpack/webpack.common.js
  webpack/webpack.dev.js
  webpack/webpack.prod.js
  yarn.lock
Labels: configuration, enhancement

#90 Efeito hover no termo 'Você sabe o que é ...?'
  src/components/Glossary/Glossary.css
  src/components/Glossary/Glossary.js
Labels: design, frontend, good first issue

#92 Adiciona efeito hover a botões
  src/components/Footer/GlossaryFooter.js
  src/components/Glossary/Glossary.css
  src/components/Glossary/Glossary.js
  src/components/search/Search.js
  src/styles/utils.css
Labels: design, enhancement, frontend
