Repository OpenDevUFCG/glossario-ufcg, pull requests merged in 2019-04, with the labels that each got.

#97 Adição de exemplos para jogos e TCC, e algumas alterações
  src/lib/disciplinas.json
Labels: Aprimoramento, Termo

#99 Trocando link do Gitter pelo do Discord
  README.md
Labels: Bug

#102 Reorganiza e renomeia componentes
  src/components/ResultCard/ResultCard.js
  src/components/app/App.js
  src/components/app/Footer/Footer.css
  src/components/app/Footer/Footer.js
  src/components/common/Icon/Icon.js
  src/components/common/IconButton/IconButton.js
  src/components/common/IconWithText/IconWithText.css
  src/components/common/IconWithText/IconWithText.js
  src/components/common/Markdown/Markdown.js
  src/components/common/Search/Search.css
  src/components/common/Search/Search.js
  src/components/common/TermCard/TermCard.css
  src/components/common/TermCard/TermCard.js
  src/components/common/index.js
  src/components/glossary/GlossaryPage.css
  src/components/glossary/GlossaryPage.js
  src/components/term/404/NotFound.js
  src/components/term/TermPage.css
  src/components/term/TermPage.js
  src/lib/data.js
Labels: Aprimoramento, Refatoramento

#104 Adiciona PyLadies como termo
  src/lib/outros.json
Labels: Aprimoramento, Termo
